module.exports = {
  defaultServerResponse: {
    status: 400,
    body: [],
    errors: {},
    message: "",
  },
  validationMessage: {
    VALIDATION_FAILED: "Validation Failed",
    TOKEN_MISSING: "Token is Missing, Login First",
  },
  adminMessage: {
    CUSTOMER_CREATED: "Admin Register Successfully!",
    PASSWORD_UPDATED: "Password Updated Successfully!",
    PASSWORD_NOT_UPDATED: "OOPS ! Password Not Updated !",
    OLD_PASSWORD_NOT_MATCHED: "OOPS ! Old Password is not Matched !",
    PROFILE_NOT_UPDATED: "OOPS ! Profile Not Updated !",
    PROFILE_UPDATED: "Profile Updated Successfully !",
    PROFILE_FETCHED: "Profile Fetched Successfully !",
    ACCOUNT_FOUND: "Account Found Successfully !",
    ACCOUNT_NOT_FOUND: "Account Not Found !",
    PROFILE_NOT_FETCHED: "OOPS ! Profile Not Fetched !",
  },
  deliveryBoyMessage: {
    DELIVERY_BOY_CREATED: "Delivery Boy Created Successfully!",
    DELIVERY_BOY_NOT_CREATED: "Delivery Boy Not Created!",
    PASSWORD_UPDATED: "Password Updated Successfully!",
    PASSWORD_NOT_UPDATED: "OOPS ! Password Not Updated !",
    OLD_PASSWORD_NOT_MATCHED: "OOPS ! Old Password is not Matched !",
    PROFILE_NOT_UPDATED: "OOPS ! Profile Not Updated !",
    PROFILE_UPDATED: "Profile Updated Successfully !",
    PROFILE_FETCHED: "Profile Fetched Successfully !",
    ACCOUNT_FOUND: "Account Found Successfully !",
    ACCOUNT_NOT_FOUND: "Account Not Found !",
    PROFILE_NOT_FETCHED: "OOPS ! Profile Not Fetched !",
    DELIVERY_BOY_FETCHED: "Delivery Boy Fetched Successfully !",
    DELIVERY_BOY_NOT_FETCHED: "Delivery Boy Not Fetched !",
    DELIVERY_BOY_UPDATED: "Delivery Boy Updated Successfully!",
    DELIVERY_BOY_NOT_UPDATED: "Delivery Boy Not Updated!",

    PINCODE_UPDATED: "Pincode Updated Successfully!",
    PINCODE_NOT_UPDATED: "Pincode Not Updated!",
  },

  supervisorMessage: {
    SUPERVISOR_CREATED: "Supervisor Created Successfully!",
    SUPERVISOR_NOT_CREATED: "Supervisor Not Created!",
    PASSWORD_UPDATED: "Password Updated Successfully!",
    PASSWORD_NOT_UPDATED: "OOPS ! Password Not Updated !",
    OLD_PASSWORD_NOT_MATCHED: "OOPS ! Old Password is not Matched !",
    PROFILE_NOT_UPDATED: "OOPS ! Profile Not Updated !",
    PROFILE_UPDATED: "Profile Updated Successfully !",
    PROFILE_FETCHED: "Profile Fetched Successfully !",
    ACCOUNT_FOUND: "Account Found Successfully !",
    ACCOUNT_NOT_FOUND: "Account Not Found !",
    PROFILE_NOT_FETCHED: "OOPS ! Profile Not Fetched !",
    SUPERVISOR_FETCHED: "Supervisor Fetched Successfully !",
    SUPERVISOR_NOT_FETCHED: "Supervisor Not Fetched !",
    SUPERVISOR_UPDATED: "Supervisor Updated Successfully!",
    SUPERVISOR_NOT_UPDATED: "Supervisor Not Updated!",
    SUPERVISOR_DELETED: "Supervisor Deleted Successfully!",
    SUPERVISOR_NOT_DELETED: "Supervisor Not Deleted!",
  },

  customerMessage: {
    CUSTOMER_CREATED: "Customer Register Successfully!",
    CUSTOMER_NOT_CREATED: "Customer Register Successfully!",

    CUSTOMER_NOT_FETCHED: "Customer not Fetched!",
    CUSTOMER_FETCHED: "Customer Fetched Successfully!",

    PROFILE_NOT_FETCHED: "Profile not Fetched!",
    PROFILE_FETCHED: "Profile Fetched Successfully!",

    ACCOUNT_VERIFIED: "Account Verify Successfully!",
    ACCOUNT_NOT_VERIFIED: "Account Not Verify!",

    CUSTOMER_NOT_DELETED: "Customer not Deleted",
    CUSTOMER_DELETED: "Customer Deleted!",
    ADDRESS_NOT_DELETE: "Address not Delete!",
    ADDRESS_NOT_UPDATED: "Address not Updated!",
    ADDRESS_NOT_FOUND: "Address not Found!",
    ADDRESS_ADDED: "Address Successfully Added!",
    ADDRESS_NOT_ADDED: "Address Not Added!",
    ADDRESS_FETCHED: "Address Fetched!",
    ADDRESS_UPDATED: "Address Successfully Updated!",
    ADDRESS_DELETED: "Address Successfully Deleted!",
    CUSTOMER_FETCHED: "Customer Profile Fetched Successfully!",
    CUSTOMER_NOT_FOUND: "Customer Not Found!",
    PROFILE_NOT_UPDATED: "Profile Not Updated!",
    PROFILE_UPDATED: "Profile Updated Successfully!",

    CUSTOMER_NOT_UPDATED: "Customer Not Updated!",
    CUSTOMER_UPDATED: "Customer Updated Successfully!",

    CUSTOMER_VERIFICATION_FAILED: "Account Verification Failed!",
    CUSTOMER_VERIFIED: "Account Verified!",
    OTP_SEND: "OTP Send to Your Email!",
    TRANSACTION_ADDED: "Transaction Added Successfully!",
    TRANSACTION_NOT_ADDED: "Transaction not Added!",
    ACCOUNT_VALIDATED: "Your Account is Validated!",
    PASSWORD_CREATED: "New Password is Created!",
    PASSWORD_NOT_CREATED: "Password Not Created!",
  },
  authMessage: {
    EMAIL_EXISTS: "Email already Exists!",
    NEED_VERIFICATION: "Account Exists, Need Verification",
    NEED_LOGIN: "Account Exists, Need Login",
    ACCOUNT_DISABLED: "Sorry Your Account is Disabled",
    INVALID_EMAIL: "Invalid Email!",
    OTP_FAILED: "OTP Failed",
    OTP_SUCCESS: "OTP Send Successfully !",
    INVALID_PASSWORD: "Password is Wrong!",
    LOGIN_SUCCESS: "Successfully Logedin",
    LOGIN_FAILED: "Login Failed !",
    REGISTRATION_SUCCESS: "Registration Successfully !",
    REGISTRATION_FAILED: "Registration Failed !",
    ACCOUNT_VALIDATED: "Account Validated Successfully !",
  },

  categoryMessage: {
    CATEGORY_CREATED: "Category Created Successfully!",
    CATEGORY_ALREADY_EXIST: "Category Already Exists!",
    CATEGORY_NOT_CREATED: "Category not Created!",
    CATEGORY_UPDATED: "Category Updated Successfully !",
    CATEGORY_NOT_UPDATED: "Category not Updated!",
    CATEGORY_DELETED: "Category Deleted Successfully!",
    CATEGORY_NOT_DELETED: "Category not Deleted!",
    CATEGORY_FETCHED: "Category Fetched Successfully!",
    CATEGORY_NOT_FETCHED: "Category not Fetched!",
    CATEGORY_NOT_FOUND: "Category not Found!",
    CATEGORY_ERROR: "OOPS Error with Category!",
  },
  occasionMessage: {
    OCCASION_CREATED: "Occassion Created Successfully!",
    OCCASION_ALREADY_EXIST: "Occassion Already Exists!",
    OCCASION_NOT_CREATED: "Occassion not Created!",
    OCCASION_UPDATED: "Occassion Updated Successfully !",
    OCCASION_NOT_UPDATED: "Occassion not Updated!",
    OCCASION_DELETED: "Occassion Deleted Successfully!",
    OCCASION_NOT_DELETED: "Occassion not Deleted!",
    OCCASION_FETCHED: "Occassion Fetched Successfully!",
    OCCASION_NOT_FETCHED: "Occassion not Fetched!",
    OCCASION_NOT_FOUND: "Occassion not Found!",
    OCCASION_ERROR: "OOPS Error with Occassion!",
  },
  newsletterMessage: {
    NEWSLETTER_CREATED: "Newsletter Created Successfully!",
    NEWSLETTER_ALREADY_EXIST: "Newsletter Already Exists!",
    NEWSLETTER_NOT_CREATED: "Newsletter not Created!",
    NEWSLETTER_UPDATED: "Newsletter Updated Successfully !",
    NEWSLETTER_NOT_UPDATED: "Newsletter not Updated!",
    NEWSLETTER_DELETED: "Newsletter Deleted Successfully!",
    NEWSLETTER_NOT_DELETED: "Newsletter not Deleted!",
    NEWSLETTER_FETCHED: "Newsletter Fetched Successfully!",
    NEWSLETTER_NOT_FETCHED: "Newsletter not Fetched!",
    NEWSLETTER_NOT_FOUND: "Newsletter not Found!",
    NEWSLETTER_ERROR: "OOPS Error with Newsletter !",
  },
  productMessage: {
    PRODUCT_CREATED: "Product Created Successfully!",
    PRODUCT_NOT_CREATED: "Product not Created!",
    PRODUCT_UPDATED: "Product Updated Successfully !",
    PRODUCT_NOT_UPDATED: "Product not Updated!",
    PRODUCT_DELETED: "Product Deleted Successfully!",
    PRODUCT_NOT_DELETED: "Product not Deleted!",
    PRODUCT_FETCHED: "Product Fetched Successfully!",
    PRODUCT_NOT_FETCHED: "Product not Fetched!",
    PRODUCT_NOT_FOUND: "Product not Found!",
    PRODUCT_ERROR: "OOPS Error with Product!",
  },
  deliveryDetailsMessage: {
    DELIVERY_DETAILS_CREATED: "Delivery Details Added Successfully!",
    DELIVERY_DETAILS_NOT_CREATED: "Delivery Details not Added!",

    DELIVERY_DETAILS_SKIPPED: "Delivery Details Skipped Successfully!",
    DELIVERY_DETAILS_NOT_SKIPPED: "Delivery Details not Skipped!",

    DELIVERY_DETAILS_UPDATED: "Delivery Details Updated Successfully !",
    DELIVERY_DETAILS_NOT_UPDATED: "Delivery Details not Updated!",

    DELIVERY_DETAILS_DELETED: "Delivery Details Deleted Successfully!",
    DELIVERY_DETAILS_NOT_DELETED: "Delivery Details not Deleted!",

    DELIVERY_DETAILS_FETCHED: "Delivery Details Fetched Successfully!",
    DELIVERY_DETAILS_NOT_FETCHED: "Delivery Details not Fetched!",

    DELIVERY_DETAILS_NOT_FOUND: "Delivery Details not Found!",
    DELIVERY_DETAILS_ERROR: "OOPS Error with Delivery Details!",

    DELIVERY_DETAILS_CANCELLED: "Delivery Details Cancelled Successfully!",
    DELIVERY_DETAILS_NOT_CANCELLED: "Delivery Details not Cancelled!",
  },

  subscriptionMessage: {
    SUBSCRIPTION_CREATED: "Subscription Purchased Successfully!",
    SUBSCRIPTION_NOT_CREATED: "Subscription not Purchased!",

    SUBSCRIPTION_RENEWAL: "Subscription Renewal Successfully!",
    SUBSCRIPTION_NOT_RENEWAL: "Subscription not Renewal!",

    SUBSCRIPTION_UPDATED: "Subscription Updated Successfully !",
    SUBSCRIPTION_NOT_UPDATED: "Subscription not Updated!",

    SUBSCRIPTION_DELETED: "Subscription Deleted Successfully!",
    SUBSCRIPTION_NOT_DELETED: "Subscription not Deleted!",

    SUBSCRIPTION_FETCHED: "Subscription Fetched Successfully!",
    SUBSCRIPTION_NOT_FETCHED: "Subscription not Fetched!",

    SUBSCRIPTION_NOT_FOUND: "Subscription not Found!",
    SUBSCRIPTION_ERROR: "OOPS Error with Subscription!",

    SUBSCRIPTION_CANCELLED: "Subscription Cancelled Successfully!",
    SUBSCRIPTION_NOT_CANCELLED: "Subscription not Cancelled!",
  },
  subscriptionHistoryMessage: {
    SUBSCRIPTION_HISTORY_CREATED: "Subscription history created!",
    SUBSCRIPTION_HISTORY_NOT_CREATED:
      "Oops ! Subscription history not created!",

    SUBSCRIPTION_HISTORY_DELETED: "Subscription Deleted Successfully!",
    SUBSCRIPTION_HISTORY_NOT_DELETED: "Subscription not Deleted!",

    SUBSCRIPTION_HISTORY_FETCHED: "Subscription Fetched Successfully!",
    SUBSCRIPTION_HISTORY_NOT_FETCHED: "Subscription not Fetched!",

    SUBSCRIPTION_HISTORY_NOT_FOUND: "Subscription not Found!",
    SUBSCRIPTION_HISTORY_ERROR: "OOPS Error with Subscription!",
  },
  bucketMessage: {
    BUCKET_CREATED: "Bucket Created Successfully!",
    BUCKET_NOT_CREATED: "Bucket not Created!",
    BUCKET_UPDATED: "Bucket Updated Successfully !",
    BUCKET_NOT_UPDATED: "Bucket not Updated!",
    BUCKET_DELETED: "Bucket Deleted Successfully!",
    BUCKET_NOT_DELETED: "Bucket not Deleted!",
    BUCKET_FETCHED: "Bucket Fetched Successfully!",
    BUCKET_NOT_FETCHED: "Bucket not Fetched!",
    BUCKET_NOT_FOUND: "Bucket not Found!",
    BUCKET_ERROR: "OOPS Error with Bucket!",
  },
  dealsMessage: {
    DEALS_CREATED: "Deals Created Successfully!",
    DEALS_NOT_CREATED: "Deals not Created!",
    DEALS_UPDATED: "Deals Updated Successfully !",
    DEALS_NOT_UPDATED: "Deals not Updated!",
    DEALS_DELETED: "Deals Deleted Successfully!",
    DEALS_NOT_DELETED: "Deals not Deleted!",
    DEALS_FETCHED: "Deals Fetched Successfully!",
    DEALS_NOT_FETCHED: "Deals not Fetched!",
    DEALS_NOT_FOUND: "Deals not Found!",
    DEALS_ERROR: "OOPS Error with Deals!",
  },

  wishlistMessage: {
    WISHLIST_CREATED: "Product Added to Wishlist !",
    PRODUCT_EXISTS: "Product Already exists in Wishlist !",
    WISHLIST_NOT_CREATED: "Wishlist not Created!",
    WISHLIST_UPDATED: "Wishlist Updated Successfully !",
    WISHLIST_NOT_UPDATED: "Wishlist not Updated!",
    WISHLIST_DELETED: "Product Deleted from Wishlist !",
    WISHLIST_NOT_DELETED: "Wishlist not Deleted!",
    WISHLIST_FETCHED: "Wishlist Fetched Successfully!",
    WISHLIST_NOT_FETCHED: "Wishlist not Fetched!",
    WISHLIST_NOT_FOUND: "Wishlist not Found!",
    WISHLIST_ERROR: "OOPS Error with Wishlist!",
  },
  couponMessage: {
    COUPON_CREATED: "Coupon Created Successfully!",
    COUPON_NOT_CREATED: "Coupon not Created!",

    COUPON_UPDATED: "Coupon Updated Successfully !",
    COUPON_NOT_UPDATED: "Coupon not Updated!",

    COUPON_DELETED: "Coupon Deleted Successfully!",
    COUPON_NOT_DELETED: "Coupon not Deleted!",

    COUPON_FETCHED: "Coupon Fetched Successfully!",
    COUPON_NOT_FETCHED: "Coupon not Fetched!",

    COUPON_NOT_FOUND: "Coupon not Found!",
    COUPON_VERIFIED: "Coupon Applied!",

    COUPON_ERROR: "Oops Error with Coupon !",
    COUPON_EXISTS: "Oops Coupon Code is already exsts !",
  },
  flavourMessage: {
    FLAVOUR_CREATED: "flavour Created Successfully !",
    FLAVOUR_NOT_CREATED: "flavour not Created!",
    FLAVOUR_UPDATED: "flavour Updated Successfully !",
    FLAVOUR_NOT_UPDATED: "flavour not Updated!",
    FLAVOUR_DELETED: "flavour Deleted Successfully!",
    FLAVOUR_NOT_DELETED: "flavour not Deleted!",
    FLAVOUR_FETCHED: "flavour Fetched Successfully!",
    FLAVOUR_NOT_FETCHED: "flavour not Fetched!",
    FLAVOUR_NOT_FOUND: "flavour not Found!",
    FLAVOUR_ERROR: "OOPS Error with flavour!",
  },
  pincodeMessage: {
    PINCODE_CREATED: "Pincode Created Successfully!",
    PINCODE_ALREADY_EXIST: "Pincode Already Exist!",
    PINCODE_NOT_CREATED: "Pincode not Created!",
    PINCODE_UPDATED: "Pincode Updated Successfully !",
    PINCODE_NOT_UPDATED: "Pincode not Updated!",
    PINCODE_DELETED: "Pincode Deleted Successfully!",
    PINCODE_NOT_DELETED: "Pincode not Deleted!",
    PINCODE_FETCHED: "Pincode Fetched Successfully!",
    PINCODE_NOT_FETCHED: "Pincode not Fetched!",
    PINCODE_NOT_FOUND: "Pincode not Found!",
    PINCODE_ERROR: "OOPS Error with Pincode!",
    PINCODE_NOT_FOR_DELIVERY:
      "Oops ! Delivery is not available for this Pincode!",
  },
  reviewMessage: {
    REVIEW_CREATED: "Review Created Successfully!",
    REVIEW_NOT_CREATED: "Review not Created!",
    REVIEW_UPDATED: "Review Updated Successfully !",
    REVIEW_NOT_UPDATED: "Review not Updated!",
    REVIEW_DELETED: "Review Deleted Successfully!",
    REVIEW_NOT_DELETED: "Review not Deleted!",
    REVIEW_FETCHED: "Review Fetched Successfully!",
    REVIEW_NOT_FETCHED: "Review not Fetched!",
    REVIEW_NOT_FOUND: "Review not Found!",
    REVIEW_ERROR: "OOPS Error with Review!",
  },
  shapeMessage: {
    SHAPE_CREATED: "Shape Created Successfully!",
    SHAPE_NOT_CREATED: "Shape not Created!",
    SHAPE_UPDATED: "Shape Updated Successfully !",
    SHAPE_NOT_UPDATED: "Shape not Updated!",
    SHAPE_DELETED: "Shape Deleted Successfully!",
    SHAPE_NOT_DELETED: "Shape not Deleted!",
    SHAPE_FETCHED: "Shape Fetched Successfully!",
    SHAPE_NOT_FETCHED: "Shape not Fetched!",
    SHAPE_NOT_FOUND: "Shape not Found!",
    SHAPE_ERROR: "OOPS Error with Shape!",
  },
  typeMessage: {
    TYPE_CREATED: "Cake Type Created Successfully!",
    TYPE_NOT_CREATED: "Cake Type not Created!",
    TYPE_UPDATED: "Cake Type Updated Successfully !",
    TYPE_NOT_UPDATED: "Cake Type not Updated!",
    TYPE_DELETED: "Cake Type Deleted Successfully!",
    TYPE_NOT_DELETED: "Cake Type not Deleted!",
    TYPE_FETCHED: "Cake Type Fetched Successfully!",
    TYPE_NOT_FETCHED: "Cake Type not Fetched!",
    TYPE_NOT_FOUND: "Cake Type not Found!",
    TYPE_ERROR: "OOPS Error with Cake Type!",
  },
  orderMessage: {
    ORDER_CREATED: "Order Created Successfully!",
    ORDER_NOT_CREATED: "Order not Created!",
    ORDER_UPDATED: "Order Updated Successfully !",
    ORDER_CANCELLED: "Order Cancelled Successfully !",
    ORDER_NOT_UPDATED: "Order not Updated!",
    ORDER_DELETED: "Order Deleted Successfully!",
    ORDER_NOT_DELETED: "Order not Deleted!",
    ORDER_FETCHED: "Order Fetched Successfully!",
    ORDER_NOT_FETCHED: "Order not Fetched!",
    ORDER_NOT_FOUND: "Order not Found!",
    ORDER_ERROR: "OOPS Error with Order!",
  },
  colorMessage: {
    COLOR_CREATED: "Color Created Successfully!",
    COLOR_NOT_CREATED: "Color not Created!",
    COLOR_UPDATED: "Color Updated Successfully !",
    COLOR_NOT_UPDATED: "Color not Updated!",
    COLOR_DELETED: "Color Deleted Successfully!",
    COLOR_NOT_DELETED: "Color not Deleted!",
    COLOR_FETCHED: "Color Fetched Successfully!",
    COLOR_NOT_FETCHED: "Color not Fetched!",
    COLOR_NOT_FOUND: "Color not Found!",
    COLOR_ERROR: "OOPS Error with Color!",
  },
  settingMessage: {
    SETTING_UPDATED: "Setting Updated Successfully !",
    SETTING_NOT_UPDATED: "Setting not Updated!",
    SETTING_FETCHED: "Setting Fetched Successfully!",
    SETTING_NOT_FETCHED: "Setting not Fetched!",
    SETTING_NOT_FOUND: "Setting not Found!",
    SETTING_ERROR: "OOPS Error with Setting!",
  },
  shippingMethodMessage: {
    SHIPPING_METHOD_CREATED: "Shipping Method Created Successfully!",
    SHIPPING_METHOD_NOT_CREATED: "Shipping Method not Created!",
    SHIPPING_METHOD_UPDATED: "Shipping Method Updated Successfully !",
    SHIPPING_METHOD_NOT_UPDATED: "Shipping Method not Updated!",
    SHIPPING_METHOD_DELETED: "Shipping Method Deleted Successfully!",
    SHIPPING_METHOD_NOT_DELETED: "Shipping Method not Deleted!",
    SHIPPING_METHOD_FETCHED: "Shipping Method Fetched Successfully!",
    SHIPPING_METHOD_NOT_FETCHED: "Shipping Method not Fetched!",
    SHIPPING_METHOD_NOT_FOUND: "Shipping Method not Found!",
    SHIPPING_METHOD_ERROR: "OOPS Error with Shipping Method!",
  },
  databaseMessage: {
    INVALID_OBJECTID: "Object ID is Invalid",
  },
};
